### PR TITLE
Custom properties

### PR DESCRIPTION
**Pull request by davidtolsma**
Add the ability to create custom properties on the docx file.

### CODE REVIEW

**Comment by jdugan** [comment]
Thanks for this.  I didn't even know custom properties were a thing.  I'll get it merged today.  

Also, I really appreciate how thoughtfully you followed all the unofficial style guidelines of the project.  Feel free to contribute anytime.

**Comment by davidtolsma** [comment]
@jdugan Thanks for merging. I'm not clear of your question, but i see it's merged. So all good?

**Comment by jdugan** [comment]
Oh, this comment was placed on the line in the commit https://github.com/trade-informatics/caracal/commit/c258928b0137568fc75d48260da588299e7b24de.  Without that context, it makes no sense. :)  I assumed GH would email you a link that went directly to the line number.

I was sure enough I was right to remove the line when I committed another small feature today.  Please feel free to object if I'm missing something.

**Comment by davidtolsma** [comment]
all good. Thanks

**Pull request merged**
