### PR TITLE
Add the possibility to set custom label size in the footer

### PR DESCRIPTION
**Pull request by cfacello**
A small commit to add the possibility of changing the text size in the footer. Defaults to 20.

### CODE REVIEW

**Comment by jdugan** [comment]
Hi, @cfacello.

I wanted to ask a follow-up question about this change.  The way you've implemented the change, the size difference only affects the text label and not the page number itself.  Was that your intent?

The reason I'm confused is because the internal parameter is named in a way that makes it clear only the label is affected, but the DSL method is just named `size`, which I think many people would assume affects both the label and the number.

I think almost all implementations of a page number would want the label and value to be the same size, so I wanted to verify whether or not you had a use case that required them to be different.  That's 100% fine--I'll just want to change the DSL slightly if that's what you needed.

(I'll make the necessary changes either way when I merge your PR.)

**Comment by cfacello** [comment]
Hi, @jdugan 

Thank you for considering this PR. As you can see, the change was only intended for the text label beacuse that was what I needed for the project I was working in. But totally I agree with you, in most cases the label and page number will be the same size. Therefore, feel free to modify it.

**Comment by jdugan** [comment]
I implemented your idea a bit differently, so I'm going to close this PR without merging it per se.  

The new version (v1.1.2) of the library reflects your idea, though, so I credited you in the change log for the enhancement. :)

**Comment by cfacello** [comment]
Great! Thank you !

**Pull request closed without merging**
