### PR TITLE
Colspan and rowspan

### PR DESCRIPTION
**Pull request by ViktorKopychko**
Hello, I've been able to implement colspan and rowspan functionallity, please take a look.

Here is the example code 
```
docx.table([[11, 1213, 14], [21, 22, 23, 24]]) do
      cell_style rows[0][0], rowspan: 2
      cell_style rows[0][1], colspan: 2
      cell_style rows[0][2], rowspan: 2
end
```
used for generating the following file
 
[example.docx](https://github.com/trade-informatics/caracal/files/2031122/example.docx)

### CODE REVIEW

**Comment by jdugan** [comment]
Awesome.  Thank you for doing this, and thank you for taking the time to do it *properly*.  PRs like this are easy to accept.  This is a long-standing request that many users will really appreciate.

Would you do me two small favours?  
1.  Please add corresponding information to the README so people know these features exist; and  
2.  It'd be nice if you squashed your commits afterward.

**Comment by ViktorKopychko** [comment]
done

**Comment by prajakta-webonise** [comment]
This is really helpful feature, @jdugan it would be great if you have a look and merge it.

**Comment by jdugan** [comment]
@ViktorKopychko Thanks again for such a meaningful feature and such a thoughtfully-coded PR.  I'll add your contribution to the changelog, bump the version, and push to rubygems shortly.

**Pull request merged**
